language: python
python:
  - "3.8"
# safelist
branches:
  only:
  - develop
services:
  - docker
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
  - docker run -d -p 8000:8000 amazon/dynamodb-local
install:
  # JavaScript test requirements
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g grunt-cli
  - sudo npm install -g bower
  - sudo npm install
  - pip install -r requirements.txt
  - pip install -U pytest
  - npm install -g serverless
# command to run tests
before_script:
  - nvm use 0.10
  - pytest test/unit/try.py -v
  - pytest test/example/TestToDo.py -v
script:
  - python --version
  - node --version
  - serverless deploy -s pre