language: python
python:
  - "3.8"
# safelist
branches:
  only:
  - develop
services:
  - docker
# command to install dependencies
before_install:
  #- python -m pip install --upgrade pip
 # - docker run -d -p 8000:8000 amazon/dynamodb-local
install:
  # JavaScript test requirements
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo apt install build-essential
  #- curl https://www.npmjs.com/install.sh | sudo sh
  #- sudo apt-get install -y npm
  #- sudo apt-get install -y nodejs
  - npm install npm@latest -g
  #- pip install -r requirements.txt
  #- pip install -U pytest
  - npm install -g serverless
# command to run tests
before_script:
 # - pytest test/unit/try.py -v
#  - pytest test/example/TestToDo.py -v
script:
  #- python --version
  - nodejs -v
  - node --version
  - serverless deploy -s pre