language: python
python:
  - "3.8"
# safelist
branches:
  only:
  - develop
services:
  - docker
# command to install dependencies
before_install:
  - python -m pip install --upgrade pip
  - docker run -d -p 8000:8000 amazon/dynamodb-local
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - npm install -g serverless
# command to run tests
before_script:
  - nvm use 0.10
  - pytest test/unit/try.py -v
  - pytest test/example/TestToDo.py -v
script:
  - serverless deploy -s pre